version: "3.8"

services:
  sls-management-ui:
    image: ghcr.io/openirl/sls-management-ui:latest
    container_name: sls-management-ui
    environment:
      REACT_APP_BASE_URL: "${APP_URL}"
      REACT_APP_SRT_PLAYER_PORT: "${SRT_PLAYER_PORT:-4000}"
      REACT_APP_SRT_SENDER_PORT: "${SRT_SENDER_PORT:-4001}"
      REACT_APP_SLS_STATS_PORT: "${SLS_STATS_PORT:-8080}"
      REACT_APP_SRTLA_PORT: "${SRTLA_PORT:-5000}"
    ports:
      - "${SLS_MGNT_PORT}:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  receiver:
    image: ghcr.io/openirl/srtla-receiver:latest
    container_name: srtla-receiver
    restart: unless-stopped
    ports:
      - "${SLS_STATS_PORT}:8080/tcp"
      - "${SRTLA_PORT}:5000/udp"
      - "${SRT_SENDER_PORT}:4001/udp"
      - "${SRT_PLAYER_PORT}:4000/udp"
    volumes:
      - ./data:/var/lib/sls
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard-backend:
    build: ./dashboard-backend
    container_name: srtla-dashboard-backend
    restart: unless-stopped
    environment:
      - RECEIVER_API=http://receiver:8080
      # Add other backend env vars here (e.g., ADMIN_USER, ADMIN_PASS)
      - PORT=8080
    ports:
      - "8081:8080" # Host:Container - API will be at localhost:8081
    depends_on:
      - receiver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard:
    build: ./dashboard
    container_name: srtla-dashboard
    environment:
      - REACT_APP_SRTLA_API=http://dashboard-backend:8080
      # Add other frontend env vars here if needed
    ports:
      - "3001:80" # Host:Container - Dashboard UI at localhost:3001
    depends_on:
      - dashboard-backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
